### ISSUE TITLE
OpenStreetMap credits

### ISSUE THREAD

**Issue by harry-wood** [petewarden/iPhoneTracker#17]
Thanks for using OpenStreetMap. This is great. Your popular app is bringing OpenStreetMap to new people. Hopefully some proportion of those people will get curious about the map, and learn how to contribute to our project.

Wow this application is popular!  How do I know? Because actually we're feeling extra strain over at (not-for-profit) OpenStreetMap.org from your users viewing the map tiles coming from our server:

<img src="http://harrywood.dev.openstreetmap.org/temp/osm_tile_ethernet_21st_April.png">

The (volunteer) sysadmin guys are in the process of bringing a new server online which will help to cope with this kind of traffic. This is hardware bought through donations to the OpenStreetMap foundation.

I wonder if you could help us out some more (here's what this "issue" is about)  The application is <b>crediting OpenStreetMap</b> a little bit more than it was previously (before it was just crediting OpenHeatMap)  but there's a little more that could be done here.  To quote from the guidelines given here: http://www.openstreetmap.org/copyright

"
If you are using OpenStreetMap map images, we request that your credit reads at least “© OpenStreetMap contributors, CC-BY-SA”.
"

"
OpenStreetMap should be hyperlinked to http://www.openstreetmap.org/ and CC-BY-SA to http://creativecommons.org/licenses/by-sa/2.0/.
"
So you should at least follow those guidelines.  A quick code change for someone (anyone!) I imagine. But beyond those legal requirements,  any other ideas you might have for helping to convert all these lovely map viewers into map contributors would be much appreciated by the OpenStreetMap community.

**Comment by petewarden** [comment]
Thanks for getting in touch Harry. Steve has been a big help to me
personally over the last couple of years, so I'm happy to do whatever I can
to support the OSM community. I've updated the credit text in the
application and added a donation link to the main page, hopefully that
should defray some of the costs. I'll also be updating my
http://www.openheatmap.com credits, but unfortunately since that's a bit
more involved, I won't be able to get to that until Friday, but please let
the community know I'm working to do the right thing here.

cheers,
           Pete

**Comment by harry-wood** [comment]
Ah yes. You've put a nice link on the homepage: http://petewarden.github.com/iPhoneTracker/   That's great thanks!
